import { CourseCardProps } from '@/components/cards/CourseCard';

// Mock data for courses
export const courses: CourseCardProps[] = [
  {
    id: '1',
    slug: 'freelance-web-development',
    title: 'Freelance Web Development Masterclass',
    description: 'Learn how to build a successful freelance web development business from scratch. This course covers everything from finding clients to delivering projects.',
    instructor: 'Sarah Johnson',
    level: 'Intermediate',
    duration: '12 hours',
    price: 199.99,
    discountPrice: 149.99,
    rating: 4.8,
    reviewCount: 245,
    imageUrl: '/web.svg',
    category: 'Freelancing',
    // format: 'video',
  },
  {
    id: '2',
    slug: 'youtube-growth-strategy',
    title: 'YouTube Growth Strategy 2023',
    description: 'Discover proven strategies to grow your YouTube channel, increase engagement, and monetize your content effectively.',
    instructor: 'Michael Chen',
    level: 'Beginner',
    duration: '8 hours',
    price: 149.99,
    rating: 4.7,
    reviewCount: 189,
    imageUrl: '/course-content-creation.svg',
    category: 'Content Creation',
    // format: 'text',
  },
  {
    id: '3',
    slug: 'stock-trading-fundamentals',
    title: 'Stock Trading Fundamentals',
    description: 'Master the basics of stock trading with practical examples and real-world case studies. Learn risk management and portfolio building.',
    instructor: 'Alex Rivera',
    level: 'Advanced',
    duration: '15 hours',
    price: 249.99,
    discountPrice: 199.99,
    rating: 4.9,
    reviewCount: 312,
    imageUrl: '/course_img.jpg',
    category: 'Trading',
    // format: 'video',
  },
  {
    id: '4',
    slug: 'digital-marketing-essentials',
    title: 'Digital Marketing Essentials',
    description: 'A comprehensive guide to digital marketing strategies including SEO, social media, email marketing, and paid advertising.',
    instructor: 'Emily Rodriguez',
    level: 'Beginner',
    duration: '10 hours',
    price: 179.99,
    discountPrice: 129.99,
    rating: 4.6,
    reviewCount: 178,
    imageUrl: '/course-marketing.svg',
    category: 'Marketing',
    // format: 'text',
  },
  {
    id: '5',
    slug: 'cryptocurrency-investing',
    title: 'Cryptocurrency Investing for Beginners',
    description: 'Learn the fundamentals of cryptocurrency investing, blockchain technology, and how to build a diversified crypto portfolio.',
    instructor: 'James Wilson',
    level: 'Beginner',
    duration: '6 hours',
    price: 129.99,
    rating: 4.5,
    reviewCount: 156,
    imageUrl: '/course-investing.svg',
    category: 'Investing',
    // format: 'video',
  },
  {
    id: '6',
    slug: 'graphic-design-freelancing',
    title: 'Graphic Design Freelancing',
    description: 'Turn your graphic design skills into a profitable freelance business. Learn client acquisition, pricing, and project management.',
    instructor: 'Lisa Thompson',
    level: 'Intermediate',
    duration: '9 hours',
    price: 169.99,
    rating: 4.7,
    reviewCount: 203,
    imageUrl: '/course-freelancing.svg',
    category: 'Freelancing',
    // format: 'text',
  },
  {
    id: '7',
    slug: 'google-digital-marketing',
    title: 'Fundamentals of Digital Marketing',
    description: 'Master the basics of digital marketing with this comprehensive course covering search, social media, display advertising, analytics and more.',
    instructor: 'Google Digital Garage',
    level: 'Beginner',
    duration: '40 hours',
    price: 0,
    rating: 4.8,
    reviewCount: 1250,
    imageUrl: '/course-marketing.svg',
    category: 'Marketing',
    // format: 'text',
    // provider: 'Google',
  },
  {
    id: '8',
    slug: 'google-data-analytics',
    title: 'Google Data Analytics Professional Certificate',
    description: 'Prepare for a career in the high-growth field of data analytics with this comprehensive program covering data cleaning, analysis, and visualization.',
    instructor: 'Google Career Certificates',
    level: 'Intermediate',
    duration: '180 hours',
    price: 0,
    rating: 4.9,
    reviewCount: 980,
    imageUrl: '/course-content-creation.svg',
    category: 'Data Science',
    // format: 'video',
    // provider: 'Google',
  },
  {
    id: '9',
    slug: 'nvidia-deep-learning',
    title: 'Fundamentals of Deep Learning',
    description: 'Learn the foundations of deep learning, including neural networks, convolutional networks, and recurrent networks with hands-on exercises.',
    instructor: 'NVIDIA Deep Learning Institute',
    level: 'Intermediate',
    duration: '20 hours',
    price: 0,
    rating: 4.7,
    reviewCount: 750,
    imageUrl: '/course-content-creation.svg',
    category: 'AI & Machine Learning',
    // format: 'video',
    // provider: 'NVIDIA',
  },
  {
    id: '10',
    slug: 'microsoft-azure-fundamentals',
    title: 'Microsoft Azure Fundamentals',
    description: 'Get started with cloud computing using Microsoft Azure. Learn core Azure concepts, services, and management tools.',
    instructor: 'Microsoft Learn',
    level: 'Beginner',
    duration: '10 hours',
    price: 0,
    rating: 4.6,
    reviewCount: 820,
    imageUrl: '/course-content-creation.svg',
    category: 'Cloud Computing',
    // format: 'text',
    // provider: 'Microsoft',
  },
];