import { CourseCardProps } from '@/components/cards/CourseCard';

// Mock data for courses
export const courses: CourseCardProps[] = [
  {
    id: '1',
    slug: 'freelance-web-development',
    title: 'Freelance Web Development Masterclass',
    description: 'Learn how to build a successful freelance web development business from scratch. This course covers everything from finding clients to delivering projects.',
    instructor: 'Sarah Johnson',
    level: 'Intermediate',
    duration: '12 hours',
    price: 199.99,
    discountPrice: 149.99,
    rating: 4.8,
    reviewCount: 245,
    imageUrl: '/course-freelancing.svg',
    category: 'Freelancing',
  },
  {
    id: '2',
    slug: 'youtube-growth-strategy',
    title: 'YouTube Growth Strategy 2023',
    description: 'Discover proven strategies to grow your YouTube channel, increase engagement, and monetize your content effectively.',
    instructor: 'Michael Chen',
    level: 'Beginner',
    duration: '8 hours',
    price: 149.99,
    rating: 4.7,
    reviewCount: 189,
    imageUrl: '/course-content-creation.svg',
    category: 'Content Creation',
  },
  {
    id: '3',
    slug: 'stock-trading-fundamentals',
    title: 'Stock Trading Fundamentals',
    description: 'Master the basics of stock trading with practical examples and real-world case studies. Learn risk management and portfolio building.',
    instructor: 'Alex Rivera',
    level: 'Advanced',
    duration: '15 hours',
    price: 249.99,
    discountPrice: 199.99,
    rating: 4.9,
    reviewCount: 312,
    imageUrl: '/course_img.jpg',
    category: 'Trading',
  },
  {
    id: '4',
    slug: 'digital-marketing-essentials',
    title: 'Digital Marketing Essentials',
    description: 'A comprehensive guide to digital marketing strategies including SEO, social media, email marketing, and paid advertising.',
    instructor: 'Emily Rodriguez',
    level: 'Beginner',
    duration: '10 hours',
    price: 179.99,
    discountPrice: 129.99,
    rating: 4.6,
    reviewCount: 178,
    imageUrl: '/course-marketing.svg',
    category: 'Marketing',
  },
  {
    id: '5',
    slug: 'cryptocurrency-investing',
    title: 'Cryptocurrency Investing for Beginners',
    description: 'Learn the fundamentals of cryptocurrency investing, blockchain technology, and how to build a diversified crypto portfolio.',
    instructor: 'James Wilson',
    level: 'Beginner',
    duration: '6 hours',
    price: 129.99,
    rating: 4.5,
    reviewCount: 156,
    imageUrl: '/course-investing.svg',
    category: 'Investing',
  },
  {
    id: '6',
    slug: 'graphic-design-freelancing',
    title: 'Graphic Design Freelancing',
    description: 'Turn your graphic design skills into a profitable freelance business. Learn client acquisition, pricing, and project management.',
    instructor: 'Lisa Thompson',
    level: 'Intermediate',
    duration: '9 hours',
    price: 169.99,
    rating: 4.7,
    reviewCount: 203,
    imageUrl: '/course-freelancing.svg',
    category: 'Freelancing',
  },
];